site_name: cs-notes
site_url: https://hrs070.github.io/cs-notes/

theme:
  name: material
  palette:
    scheme: slate  # Dark mode

docs_dir: docs
use_directory_urls: true

nav:
  - Home: index.md
  - Tips & Snippets: tips-and-snippets.md
  - Clean Code: cleanCode.md
  - Principles:
    - SOLID: principles/solid.md
    - ATOM: principles/atom.md
  - DevOps:
    - Kubernetes (k8s):
      - Basics: devops/k8s/basics.md
      - Pods: devops/k8s/pods.md
      - Deployment: devops/k8s/deployment.md